server:
  port: ${port:6868} #服务端口

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中心，本身就是所有无需注册
    fetchRegistry: false #是否从Eureka中获取注册信息
    #serviceUrl: #Eureka客户端与Eureka服务端交互的地址
      #defaultZone: http://lenovo:lenovo123@127.0.0.1:6868/eureka/

spring:
  application:
    name: lenovo-microservice-eureka #指定服务名

security:
  basic:
    enable: true #开启基于HTTP basic的认证
  user: #配置用户的账号信息
    name: lenovo
    password: lenovo123
